apiVersion: v1
kind: Service
metadata:
  name: chat-app-service
spec:
  type: NodePort
  selector:
    app: chat-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32000
