name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build and Push Docker Image
      run: |
        docker build -t muneebdocker/chat-app:latest .
        echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
        docker push muneebdocker/chat-app:latest

    - name: List Docker Images
      run: docker images

    - name: Deploy Application
      run: |
        docker run -d --name chat-app -p 3000:3000 muneebdocker/chat-app:latest
